#!/usr/bin/env bash
# This script displays information about subdomains

display_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub"."$domain")

        if [ -z "$result" ]; then
            echo "The subdomain $sub does not exist."
        else
            record_type=$(dig "$sub"."$domain" | awk '/^'"$sub"'\.'"$domain"'\./ {print $4}')
            echo "The subdomain $sub is a $record_type record and points to $result"
        fi
    done
}

display_info "$1" "$2"
