#!/usr/bin/env bash
# Script to install and configure Nginx

apt-get update -y
apt-get install -y nginx
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
service nginx restart
echo "Hello World!" > /var/www/html/index.html
echo "Nginx installed and configured successfully. Web server is now listening on port 8080."
