#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me to another page with a 301 Moved Permanently

echo "location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }" | tee -a /etc/nginx/sites-available/default > /dev/null
/etc/init.d/nginx restart
