#!/usr/bin/env bash
# Install and configure Nginx with a custom 404 page.

apt-get update
apt-get install -y nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "error_page 404 /404.html;" > /etc/nginx/sites-available/default
/etc/init.d/nginx restart
