#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sitesavailable/default /etc/nginx/sites-enabled/default
service restart nginx
