#!/usr/bin/env bash
# Configure Nginx to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
(sleep 1 && service nginx stop) & service nginx start
(sleep 1 && ! service nginx status | grep -q "nginx is running") && echo " * nginx is not running"
