#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2 seconds.
# It also prints "I am invincible!!!" when receiving a SIGTERM signal.

# Function to handle SIGTERM signal
function handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal to invoke the function
trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
