#!/usr/bin/env bash
# This script displays the content of the current directory in list format
for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done
