#!/usr/bin/env bash
# Start Apache and configure it to return a page containing Hello Holberton

apt-get update
apt-get install -y apache2
service apache2 start
echo "<html><head></head><body>Hello Holberton</body></html>" > /var/www/html/index.html
service apache2 status
echo "Apache is now running and configured to return a page with Hello Holberton"
