#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port

sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
nginx -g 'daemon off;'
