#!/usr/bin/env bash
sed -i 's/^user.*/user nginx;/' /etc/nginx/nginx.conf
grep -q "listen 8080;" /etc/nginx/nginx.conf || sed -i "/^\s*http {/a\    listen 8080;" /etc/nginx/nginx.conf
service nginx restart
