#!/usr/bin/env bash
# This script creates an RSA key pair with specific requirements

private_key="school"
public_key="${private_key}.pub"

ssh-keygen -t rsa -b 4096 -f "$private_key" -N "betty"

echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $public_key."
echo "The key fingerprint is:"
ssh-keygen -lf "$private_key"
echo "The key's randomart image is:"
ssh-keygen -lvf "$private_key"

ls "$private_key" "$public_key"
